window.PREPLAB_QUESTIONS = {
  sentenceCompletion: [
    {id:"SC-001", difficulty:1, question:"The guide spoke slowly so that everyone could ____ the instructions.", options:["ignore","follow","hide","replace"], answer:1, explanation:"If someone speaks slowly, the goal is usually to help people follow or understand instructions."},
    {id:"SC-002", difficulty:1, question:"The museum is closed on Mondays but is ____ on all other weekdays.", options:["open","heavy","silent","remote"], answer:0, explanation:"The contrast with closed points to open."},
    {id:"SC-003", difficulty:2, question:"Regular exercise can ____ the risk of certain health problems.", options:["reduce","borrow","invent","delay"], answer:0, explanation:"Exercise can lower/reduce risk."},
    {id:"SC-004", difficulty:2, question:"The committee reached a decision only after a long and careful ____.", options:["celebration","discussion","journey","prediction"], answer:1, explanation:"Committees reach decisions through discussion."},
    {id:"SC-005", difficulty:3, question:"Although the first results seemed promising, the researchers remained ____ until further evidence was collected.", options:["skeptical","careless","furious","ordinary"], answer:0, explanation:"Although promising creates a contrast: they stayed cautious/skeptical."},
    {id:"SC-006", difficulty:3, question:"The village was almost completely ____ after the river flooded its main streets.", options:["abandoned","illuminated","translated","measured"], answer:0, explanation:"A flood can force people to leave, so abandoned fits."},
    {id:"SC-007", difficulty:4, question:"The historian's claim was difficult to verify because the surviving records were ____ and often contradictory.", options:["fragmentary","generous","portable","obedient"], answer:0, explanation:"Fragmentary records are incomplete, making verification hard."},
    {id:"SC-008", difficulty:4, question:"The new policy was intended to ____ the effects of rising food prices on low-income families.", options:["mitigate","decorate","imitate","postpone"], answer:0, explanation:"Mitigate means make less severe."},
    {id:"SC-009", difficulty:5, question:"The critic praised the novel's prose but found its plot unnecessarily ____ and difficult to follow.", options:["convoluted","transparent","durable","frugal"], answer:0, explanation:"Convoluted means overly complicated."},
    {id:"SC-010", difficulty:5, question:"Rather than offering a definitive answer, the study merely ____ several possible explanations.", options:["enumerated","abolished","resembled","withstood"], answer:0, explanation:"Enumerated means listed."},
    {id:"SC-011", difficulty:3, question:"The ancient city was protected by walls that were ____ enough to withstand repeated attacks.", options:["sturdy","fragile","minor","casual"], answer:0, explanation:"Walls that withstand attacks are sturdy."},
    {id:"SC-012", difficulty:2, question:"Because the evidence was weak, the judge decided to ____ the case.", options:["dismiss","expand","decorate","whisper"], answer:0, explanation:"A weak case may be dismissed."},
    {id:"SC-013", difficulty:4, question:"The speaker's argument was persuasive because it was supported by ____ data rather than personal opinion.", options:["empirical","fictional","decorative","accidental"], answer:0, explanation:"Empirical data is based on observation or evidence."},
    {id:"SC-014", difficulty:1, question:"The library asks visitors to remain ____ while others are reading.", options:["quiet","hungry","ancient","distant"], answer:0, explanation:"Quiet fits a library context."},
    {id:"SC-015", difficulty:5, question:"Her response was so ____ that nobody could tell whether she agreed or disagreed.", options:["ambiguous","reckless","abundant","horizontal"], answer:0, explanation:"Ambiguous means unclear or open to more than one interpretation."}
  ],
  restatement: [
    {id:"RS-001", difficulty:1, question:"Most people cannot buy everything they want.", options:["Most people have enough money for everything.","Most people want only what they can buy.","Most people do not have enough money to buy all the things they want.","People usually buy more than they want."], answer:2, explanation:"The meaning is that wants exceed available money."},
    {id:"RS-002", difficulty:2, question:"The island is famous for its unusual wildlife.", options:["The island is known because of the unusual animals that live there.","The island's wildlife is ordinary.","Few people know about the island's animals.","The island became famous before animals lived there."], answer:0, explanation:"Famous for = known because of."},
    {id:"RS-003", difficulty:2, question:"Although the plan was expensive, it solved the problem effectively.", options:["The plan failed because it cost too much.","The plan worked well despite its high cost.","The plan was cheap and effective.","The plan was expensive because it did not solve the problem."], answer:1, explanation:"Although signals contrast: expensive but effective."},
    {id:"RS-004", difficulty:3, question:"Few inventions have changed daily life as much as the telephone.", options:["The telephone changed daily life more than many other inventions.","Most inventions changed the telephone.","The telephone has had little effect on daily life.","Daily life changed before the telephone was invented."], answer:0, explanation:"Few as much as = it is among the most influential."},
    {id:"RS-005", difficulty:3, question:"The author was admired not only for her novels but also for her essays.", options:["People admired only the author's novels.","The author's essays were admired as well as her novels.","The author stopped writing novels and wrote essays.","Her essays were admired more than her novels."], answer:1, explanation:"Not only... but also means both."},
    {id:"RS-006", difficulty:4, question:"No reliable conclusion can be drawn from a sample this small.", options:["A small sample can produce only reliable conclusions.","The sample is too small to support a dependable conclusion.","The conclusion is reliable because the sample is small.","The sample was drawn after the conclusion."], answer:1, explanation:"No reliable conclusion = not enough evidence."},
    {id:"RS-007", difficulty:4, question:"The discovery was attributed to Newton, although several scientists had contributed to the theory earlier.", options:["Newton was credited with the discovery even though others had helped develop the theory.","Newton refused to accept credit for the theory.","Several scientists discovered that Newton was wrong.","The theory was developed only after Newton's discovery."], answer:0, explanation:"Attributed to = credited to; although = despite prior contributions."},
    {id:"RS-008", difficulty:5, question:"The policy's effects were negligible until economic conditions deteriorated sharply.", options:["The policy had little effect before the economy became much worse.","The policy caused the economy to improve immediately.","Economic conditions were negligible because of the policy.","The policy was cancelled before the economy changed."], answer:0, explanation:"Negligible means very small; deteriorated sharply means became much worse."}
  ],
  reading: [
    {
      id:"RC-001", difficulty:2, title:"The Return of Urban Bees",
      passage:"In many large cities, small green spaces have become unexpectedly important to bees. Parks, balconies, and rooftop gardens provide flowers at different times of the year, sometimes more consistently than fields in rural areas where a single crop may dominate the landscape. As a result, some urban beekeepers report that their hives are surprisingly productive. Scientists caution, however, that city life is not automatically safe for bees. Pollution, pesticides used in private gardens, and the loss of nesting places can still threaten them. The most successful urban bee projects are therefore not simply about placing hives on rooftops. They also involve planting diverse flowers, avoiding harmful chemicals, and educating residents about the role of pollinators.",
      questions:[
        {id:"RC-001-Q1", type:"main_idea", difficulty:2, question:"What is the main purpose of the passage?", options:["To explain why urban spaces can help bees but also present risks","To prove that rural areas are always bad for bees","To describe the history of rooftop gardening","To compare bees with other city animals"], answer:0, explanation:"The passage balances benefits and risks of urban spaces for bees."},
        {id:"RC-001-Q2", type:"detail", difficulty:1, question:"According to the passage, why may city green spaces help bees?", options:["They contain no people","They may provide flowers at different times of year","They are usually larger than farms","They prevent all pollution"], answer:1, explanation:"The passage says parks, balconies, and rooftops can provide flowers at different times."},
        {id:"RC-001-Q3", type:"inference", difficulty:3, question:"It can be inferred that simply adding hives to a city is not enough because ____.", options:["bees cannot fly in cities","residents always oppose bees","bees also need safe habitats and varied food sources","rural bees are more intelligent"], answer:2, explanation:"The final sentence says successful projects include flowers, avoiding chemicals, and education."},
        {id:"RC-001-Q4", type:"vocabulary", difficulty:2, question:"In the passage, 'diverse' is closest in meaning to ____.", options:["varied","expensive","hidden","temporary"], answer:0, explanation:"Diverse flowers are varied flowers."},
        {id:"RC-001-Q5", type:"purpose", difficulty:3, question:"Why does the author mention pollution and pesticides?", options:["To show that city life may still be dangerous for bees","To argue that bees cause pollution","To explain why rooftop gardens are impossible","To show that rural areas have no pesticides"], answer:0, explanation:"These are examples of threats bees face in cities."}
      ]
    },
    {
      id:"RC-002", difficulty:4, title:"Maps and Memory",
      passage:"Before digital navigation became common, travelers often learned the shape of a city by getting lost in it. They remembered a bakery near a narrow bridge, a noisy square, or a street that curved unexpectedly. Today, a phone can guide a person from one point to another with remarkable efficiency. Yet some researchers argue that this convenience may reduce the kind of spatial memory developed through active exploration. When people follow turn-by-turn instructions, they may arrive quickly without forming a mental map of the area. This does not mean that navigation technology is harmful in itself. For emergency workers, tourists, and delivery drivers, it can be extremely useful. The question is whether people should occasionally put the device away and let attention, rather than instructions, guide them through unfamiliar streets.",
      questions:[
        {id:"RC-002-Q1", type:"main_idea", difficulty:3, question:"The passage mainly discusses ____.", options:["the possible effect of digital navigation on spatial memory","the invention of mobile phones","why delivery drivers dislike maps","the history of bakeries in cities"], answer:0, explanation:"The passage focuses on navigation technology and mental maps."},
        {id:"RC-002-Q2", type:"detail", difficulty:3, question:"According to the passage, people may develop spatial memory by ____.", options:["following instructions exactly","actively exploring places","avoiding unfamiliar streets","using only emergency routes"], answer:1, explanation:"The passage contrasts active exploration with turn-by-turn instructions."},
        {id:"RC-002-Q3", type:"inference", difficulty:4, question:"The author would probably agree that digital navigation ____.", options:["should never be used","is useful but should not replace all active attention","is only helpful in small towns","always improves memory"], answer:1, explanation:"The passage says it is useful but raises a question about relying on it too much."},
        {id:"RC-002-Q4", type:"vocabulary", difficulty:4, question:"In the passage, 'efficiency' is closest in meaning to ____.", options:["speed and effectiveness","confusion","beauty","danger"], answer:0, explanation:"Efficiency means doing something quickly and effectively."},
        {id:"RC-002-Q5", type:"purpose", difficulty:5, question:"Why does the author mention emergency workers and tourists?", options:["To show groups for whom navigation technology can be very useful","To claim that only tourists use maps","To argue that emergency workers should get lost","To show that tourists have better memory"], answer:0, explanation:"They are examples of people who benefit from navigation technology."}
      ]
    }
  ]
};
